### ISSUE TITLE
存在与B站无关的项目

### ISSUE THREAD

**Issue by jiwangyihao** [HCLonely/awesome-bilibili-extra#7]
在下载类别中有一个「下载哔哩轻小说并导出至epub」的项目（

哔哩轻小说：https://www.bilinovel.com
曾用地址：https://w.linovelib.com

这个网站和哔哩哔哩无关，是一个轻小说网站（

**Comment by HCLonely** [comment]
已处理

**Comment by jiwangyihao** [comment]
@HCLonely 
[Bilinovel-download](https://github.com/ShqWW/bilinovel-download)
[Bili_novel_packer](https://github.com/Montaro2017/bili_novel_packer)

同上（
